import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import image from "../public/main.jpg";
import Image from "next/image";
import Navigation from "@/components/navigation/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="background__wrapper">
          <Navigation />
          {children}
          <Image className="background__image" fill={true} src={image} alt="" />
        </div>
      </body>
    </html>
  );
}
